import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarWrapper from "@/components/nav-bar/layout/NavBarWrapper";
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from "@/context/CartContext";
import FloatingCartButton from "@/components/FloatingCartButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <div className="h-16">
            <NavBarWrapper />
          </div>
          <main className="px-4">{children}</main>

          <Toaster />
          <FloatingCartButton />
        </CartProvider>
      </body>
    </html>
  );
}
